---
title: "Quality Check"
author: "Dian Li"
date: "2021-02-25"
output: 
  workflowr::wflow_html:
    toc: false
    number_sections: false
    toc_depth: 2
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache = FALSE, message = FALSE)
library(workflowr)
```

## **Heatmap - Correlation** 

```{r, message=FALSE, warning=FALSE}
library(workflowr)
# library(ggfortify)
library(ComplexHeatmap)
library(openxlsx)
library(circlize)
```

```{r, message=FALSE, warning=FALSE,fig.width = 10,fig.height=10}
filePath = ("../private_data/210225/batch 2.xlsx")
df = read.xlsx(filePath, rowNames = TRUE, check.names = T)
head(df)

cor_res = cor((df[,-which(colnames(df)=="GFP1")]))
print(Heatmap(cor_res, 
              col = colorRamp2(c(min(cor_res, na.rm = T), 0, c(max(cor_res, na.rm = T))), c("blue", "white", "red")),
              na_col = "black",
              column_title = paste0("Correlation Heatmap"),
              heatmap_legend_param = list(title = "Pearson\nCorrelation")))

cor_res = cor(t(df))
print(Heatmap(cor_res, 
              col = colorRamp2(c(min(cor_res, na.rm = T), 0, c(max(cor_res, na.rm = T))), c("blue", "white", "red")),
              na_col = "black",
              column_title = paste0("Correlation Heatmap"),
              heatmap_legend_param = list(title = "Pearson\nCorrelation")))
```

-----

## **Heatmap - Expression ** 
```{r, message=FALSE, warning=FALSE,fig.width = 5,fig.height=10}
min_val = min(df[,], na.rm = T)
max_val = max(df[,], na.rm = T)
mid_val = (min_val + max_val) / 2
           
print(Heatmap(df[,], 
              col = colorRamp2(c(min_val, mid_val, max_val), c("blue", "white", "red")),
              na_col = "black",
              column_title = paste0("Expression Heatmap"),
              heatmap_legend_param = list(title = "Expression\nLevel")))
```         


-----

## **Heatmap - Expression wo MAPT ** 
```{r, message=FALSE, warning=FALSE,fig.width = 5,fig.height=10}
df_1 = df[-which(rownames(df) == "MAPT"),]

min_val = min(df_1, na.rm = T)
max_val = max(df_1, na.rm = T)
mid_val = (min_val + max_val) / 2
           
print(Heatmap(df_1, 
              col = colorRamp2(c(min_val, mid_val, max_val), c("blue", "white", "red")),
              na_col = "black",
              column_title = paste0("Expression Heatmap wo MAPT"),
              heatmap_legend_param = list(title = "Expression\nLevel")))
```    


-----

## **Heatmap - Expression wo MAPT | Majorsat** 
```{r, message=FALSE, warning=FALSE,fig.width = 5,fig.height=10}
df_1 = df[-which((rownames(df) == "MAPT") | (rownames(df) == "Majorsat")),]

min_val = min(df_1, na.rm = T)
max_val = max(df_1, na.rm = T)
mid_val = (min_val + max_val) / 2
           
print(Heatmap(df_1, 
              col = colorRamp2(c(min_val, mid_val, max_val), c("blue", "white", "red")),
              na_col = "black",
              column_title = paste0("Expression Heatmap wo MAPT|Majorsat"),
              heatmap_legend_param = list(title = "Expression\nLevel")))
``` 


-----

## **Heatmap - Expression wo MAPT | Majorsat | S100b** 
```{r, message=FALSE, warning=FALSE,fig.width = 5,fig.height=10}
df_1 = df[-which((rownames(df) == "MAPT") | (rownames(df) == "Majorsat") | (rownames(df) == "S100b")),]

min_val = min(df_1, na.rm = T)
max_val = max(df_1, na.rm = T)
mid_val = (min_val + max_val) / 2
           
print(Heatmap(df_1, 
              col = colorRamp2(c(min_val, mid_val, max_val), c("blue", "white", "red")),
              na_col = "black",
              column_title = paste0("Expression Heatmap wo MAPT|Majorsat|S100b"),
              heatmap_legend_param = list(title = "Expression\nLevel")))
``` 

-----

## **Heatmap - Expression wo MAPT | Majorsat | S100b | Sting1** 
```{r, message=FALSE, warning=FALSE,fig.width = 5,fig.height=10}
df_1 = df[-which((rownames(df) == "MAPT") | (rownames(df) == "Majorsat") | (rownames(df) == "S100b") | (rownames(df) == "Sting1")),]

min_val = min(df_1, na.rm = T)
max_val = max(df_1, na.rm = T)
mid_val = (min_val + max_val) / 2
           
print(Heatmap(df_1, 
              col = colorRamp2(c(min_val, mid_val, max_val), c("blue", "white", "red")),
              na_col = "black",
              column_title = paste0("Expression wo MAPT|Majorsat|S100b|Sting1"),
              heatmap_legend_param = list(title = "Expression\nLevel")))
``` 
       